---
title: "HCAMP Baseline and Post-Injury Analysis"
output:
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
    highlight: tango 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r, include=FALSE}
library(tidyverse)
library(here)
library(janitor)
library(rio)
library(colorblindr)
library(gghighlight)
library(forcats)
library(ggrepel)
library(gt)
library(knitr)
library(kableExtra)
library(reactable)
library(plotly)
library(glue)
library(fs)
library(rstatix)
library(ggpubr)

theme_set(theme_minimal(15) +
            theme(legend.position = "bottom",
                  panel.grid.major.x = element_line(color = "gray60"),
                  panel.grid.minor.x = element_blank(),
                  panel.grid.major.y = element_blank())
          )


files <- dir_ls(here::here("data"), glob = "*.csv")

d <- map_df(files, read_csv, .id = "file",
                 col_types = cols(.default = "c")) %>% 
  modify(~parse_guess(.x)) %>% 
  janitor::clean_names() %>% 
  mutate(year = parse_number(file)) %>% 
  mutate(year = as.factor(year))

mean_2 <- function(x) {
  z <- na.omit(x)
  sum(z) / length(z)
}

str(d)
d$user_symptom22delayed
d$user_symptom11delayed

impact2 <- d %>% 
  mutate(user_gender = as.factor(user_gender),
         user_age = as.factor(user_age),
         org_name = as.factor(org_name),
         user_handedness = as.factor(user_handedness),
         user_height = as.factor(user_height),
         user_weight = as.factor(user_weight),
         user_country = as.factor(user_country),
         user_first_language = as.factor(user_first_language),
         user_second_language = as.factor(user_second_language),
         user_education_level = as.factor(user_education_level),
         user_special_ed1 = as.factor(user_special_ed1),
         user_special_ed2 = as.factor(user_special_ed2),
         user_special_ed3 = as.factor(user_special_ed3),
         user_special_ed4 = as.factor(user_special_ed4),
         user_special_ed5 = as.factor(user_special_ed5),
         add_adhd = as.factor(add_adhd),
         dyslexia = as.factor(dyslexia),
         autism = as.factor(autism),
         user_treatment_received1 = as.factor(user_treatment_received1),
         user_treatment_received2 = as.factor(user_treatment_received2),
         user_treatment_received3 = as.factor(user_treatment_received3),
         user_treatment_received4 = as.factor(user_treatment_received4),
         user_treatment_received5 = as.factor(user_treatment_received5),
         user_treatment_received6 = as.factor(user_treatment_received6),
         user_treatment_received7 = as.factor(user_treatment_received7),
         user_current_sport = as.factor(user_current_sport),
         user_primary_position = as.factor(user_primary_position),
         user_level_of_participation = as.factor(user_level_of_participation),
         user_years_playing = as.factor(user_years_playing),
         user_number_of_concussions = as.factor(user_number_of_concussions),
         user_concussion_type1 = as.factor(user_concussion_type1),
         user_concussion_type2 = as.factor(user_concussion_type2),
         user_concussion_type3 = as.factor(user_concussion_type3),
         user_concussion_type4 = as.factor(user_concussion_type4),
         user_total_games_missed = as.factor(user_total_games_missed),
         user_concussion_history = as.factor(user_concussion_history),
         user_last_concussion_date = as.factor(user_last_concussion_date),
         test_type = as.factor(test_type),
         test_date = as.factor(test_date),
         exam_language = as.factor(exam_language),
         test_version = as.factor(test_version),
         word_memory_lp = as.factor(word_memory_lp),
         word_memory_dm_correct = as.factor(word_memory_dm_correct),
         word_memory_total_percent_correct = as.factor(word_memory_total_percent_correct),
         design_memory_lp = as.factor(design_memory_lp),
         design_memory_dm_correct = as.factor(design_memory_dm_correct),
         design_memory_total_percent_correct = as.factor(design_memory_total_percent_correct),
         x_oaverage_incorrect = as.factor(x_oaverage_incorrect),
         three_letters_percentage_letters_correct = as.factor(three_letters_percentage_letters_correct),
         user_symptom1delayed = as.factor(user_symptom1delayed))

str(impact2)

impact2$user_symptom1delayed


impact3 <- impact2 %>% 
  mutate(user_age = as.numeric(user_age),
         user_height = as.numeric(user_height),
         user_weight = as.numeric(user_weight),
         user_education_level = as.numeric(user_education_level),
         user_years_playing = as.numeric(user_years_playing),
         user_number_of_concussions = as.numeric(user_number_of_concussions),
         user_concussion_type1 = as.numeric(user_concussion_type1),
         user_concussion_type2 = as.numeric(user_concussion_type2),
         user_concussion_type3 = as.numeric(user_concussion_type3),
         user_concussion_type4 = as.numeric(user_concussion_type4),
         user_total_games_missed = as.numeric(user_total_games_missed),
         word_memory_lp = as.numeric(word_memory_lp),
         word_memory_dm_correct = as.numeric(word_memory_dm_correct),
         word_memory_total_percent_correct = as.numeric(word_memory_total_percent_correct),
         design_memory_lp = as.numeric(design_memory_lp),
         design_memory_dm_correct = as.numeric(design_memory_dm_correct),
         design_memory_total_percent_correct = as.numeric(design_memory_total_percent_correct),
         x_oaverage_incorrect = as.numeric(x_oaverage_incorrect),
         three_letters_percentage_letters_correct = as.numeric(three_letters_percentage_letters_correct),
         user_symptom1delayed = as.numeric(user_symptom1delayed))

str(impact3)

mean_2(impact3$user_symptom1delayed)
mean_2(impact3$user_symptom2delayed)
mean_2(impact3$user_age)

impact <- impact3

str(impact)

impact$user_current_sport
```

```{r code needed for rest of document, include=FALSE}

test_time_baseline <- impact %>% 
  select(year,
         passport_id, 
         user_gender, 
         user_age, 
         org_name,
         test_type, 
         test_date, 
         test_version, 
         user_current_sport,
         user_number_of_concussions,
         user_education_level,
         user_memory_composite_score_verbal,
         user_memory_composite_score_visual,
         user_impulse_control_composite_score,
         user_visual_motor_composite_score,
         user_reaction_time_composite_score,
         user_impulse_control_composite_score) 

str(test_time_baseline)

test_time_baseline <- test_time_baseline %>% 
  filter(test_type != "Baseline ++")

test_time_baseline <- test_time_baseline %>% 
  filter(test_type != "Post-Injury 2")

test_time_baseline <- test_time_baseline %>% 
  filter(test_type != "Post-Injury 3")

test_time_baseline <- test_time_baseline %>% 
  filter(test_type != "Post-Injury 4")


test_time_baseline %>% 
  arrange(passport_id)

baseline <- test_time_baseline %>% 
  filter(test_type == "Baseline") 

str(baseline)

baseline3 <- baseline %>% 
  group_by(passport_id) %>% 
  filter(n() > 1) %>% 
  mutate(baseline_number = row_number()) %>% 
  spread(baseline_number, test_type, sep = "_") %>% 
  arrange(passport_id)


baseline3 <- baseline3[, -c(18:24)]

str(baseline3)

baseline3 %>% 
  count(passport_id)


head(baseline3)

baseline3$test_date <- as.Date(baseline3$test_date, format = "%m/%d/%Y")

mem_verbal <- baseline3 %>% 
  group_by(passport_id) %>% 
  mutate(number = row_number()) %>% 
  ungroup() %>% 
  pivot_wider(
    id_cols = passport_id,
    names_from = number,
    values_from = c(test_date, user_memory_composite_score_verbal),
    names_glue = "{.value}_{number}"
  ) 

mem_verbal <- mem_verbal %>% 
  select(passport_id, 
         test_date_1, 
         test_date_2, 
         user_memory_composite_score_verbal_1, 
         user_memory_composite_score_verbal_2) %>% 
  mutate(memory_verbal_diff = user_memory_composite_score_verbal_2 - user_memory_composite_score_verbal_1)

mem_verbal_all <- mem_verbal

mem_verbal <- mem_verbal %>% 
  filter(memory_verbal_diff > 0)

mem_verbal <- mem_verbal %>% 
  mutate(memory_verbal_percent_inc = memory_verbal_diff / user_memory_composite_score_verbal_1 * 100)

mean_2(mem_verbal$memory_verbal_diff)
mean_2(mem_verbal$memory_verbal_percent_inc)

mem_visual <- baseline3 %>% 
  group_by(passport_id) %>% 
  mutate(number = row_number()) %>% 
  ungroup() %>% 
  pivot_wider(
    id_cols = passport_id,
    names_from = number,
    values_from = c(test_date, user_memory_composite_score_visual),
    names_glue = "{.value}_{number}"
  ) 

mem_visual <- mem_visual %>% 
  select(passport_id, 
         test_date_1, 
         test_date_2, 
         user_memory_composite_score_visual_1, 
         user_memory_composite_score_visual_2) %>% 
  mutate(memory_visual_diff = user_memory_composite_score_visual_2 - user_memory_composite_score_visual_1)

mem_visual_all <- mem_visual

mem_visual <- mem_visual %>% 
  filter(memory_visual_diff > 0)

mean_2(mem_visual$memory_visual_diff)

mem_visual <- mem_visual %>% 
  mutate(memory_visual_percent_inc = memory_visual_diff / user_memory_composite_score_visual_1 * 100)

visual_motor <- baseline3 %>% 
  group_by(passport_id) %>% 
  mutate(number = row_number()) %>% 
  ungroup() %>% 
  pivot_wider(
    id_cols = passport_id,
    names_from = number,
    values_from = c(test_date, user_visual_motor_composite_score),
    names_glue = "{.value}_{number}"
  ) 

visual_motor <- visual_motor %>% 
  select(passport_id, 
         test_date_1, 
         test_date_2, 
         user_visual_motor_composite_score_1, 
         user_visual_motor_composite_score_2) %>% 
  mutate(visual_motor_diff = user_visual_motor_composite_score_2 - user_visual_motor_composite_score_1)

visual_motor_all <- visual_motor

visual_motor <- visual_motor %>% 
  filter(visual_motor_diff > 0)

visual_motor <- visual_motor %>% 
  mutate(visual_motor_percent_inc = visual_motor_diff / user_visual_motor_composite_score_1 * 100)


impulse_control <- baseline3 %>% 
  group_by(passport_id) %>% 
  mutate(number = row_number()) %>% 
  ungroup() %>% 
  pivot_wider(
    id_cols = passport_id,
    names_from = number,
    values_from = c(test_date, user_impulse_control_composite_score),
    names_glue = "{.value}_{number}"
  ) 

impulse_control <- impulse_control %>% 
  select(passport_id, 
         test_date_1, 
         test_date_2, 
         user_impulse_control_composite_score_1, 
         user_impulse_control_composite_score_2) %>% 
  mutate(impulse_control_diff = user_impulse_control_composite_score_1 - user_impulse_control_composite_score_2)

impulse_control_all <- impulse_control

impulse_control <- impulse_control %>% 
  filter(impulse_control_diff > 0)

impulse_control <- impulse_control %>% 
  mutate(impulse_control_percent_dec = impulse_control_diff / user_impulse_control_composite_score_1 * 100)

reaction_time <- baseline3 %>% 
  group_by(passport_id) %>% 
  mutate(number = row_number()) %>% 
  ungroup() %>% 
  pivot_wider(
    id_cols = passport_id,
    names_from = number,
    values_from = c(test_date, user_reaction_time_composite_score),
    names_glue = "{.value}_{number}"
  ) 

reaction_time <- reaction_time %>% 
  select(passport_id, 
         test_date_1, 
         test_date_2, 
         user_reaction_time_composite_score_1, 
         user_reaction_time_composite_score_2) %>% 
  mutate(reaction_time_diff = user_reaction_time_composite_score_1 - user_reaction_time_composite_score_2)

reaction_time_all <- reaction_time

reaction_time <- reaction_time %>% 
  filter(reaction_time_diff > 0)

reaction_time <- reaction_time %>% 
  mutate(reaction_time_percent_dec = reaction_time_diff / user_reaction_time_composite_score_1 * 100)


mem_verbal <- mem_verbal %>% 
  arrange(passport_id) %>% 
  na.omit()

mem_verbal_all <- mem_verbal_all %>% 
  na.omit()

mem_visual <- mem_visual %>% 
  arrange(passport_id) %>% 
  na.omit()

mem_visual_all <- mem_visual_all %>% 
  na.omit()

impulse_control <- impulse_control %>% 
  arrange(passport_id) %>% 
  na.omit()

impulse_control_all <- impulse_control_all %>% 
  na.omit()

reaction_time <- reaction_time %>% 
  arrange(passport_id) %>% 
  na.omit()

reaction_time_all <- reaction_time_all %>% 
  na.omit()

visual_motor <- visual_motor %>% 
  arrange(passport_id) %>% 
  na.omit()

visual_motor_all <- visual_motor_all %>% 
  na.omit()

test_join <- full_join(mem_verbal, mem_visual)

test_join2 <- full_join(test_join, impulse_control)

test_join3 <- full_join(test_join2, reaction_time)

baseline_final <- full_join(test_join3, visual_motor)
head(baseline_final)

mean_2(impulse_control$impulse_control_diff)
mean_2(baseline_final$impulse_control_diff)


baseline_all_positive <- baseline_final %>% 
  na.omit()


mem_verbal %>% 
  summarize(Mean = mean(memory_verbal_diff),
            SD = sd(memory_verbal_diff),
            Min = min(memory_verbal_diff),
            Max = max(memory_verbal_diff),
            Total = length(memory_verbal_diff)) %>% 
  mutate_if(is.numeric, round, 2) %>% 
  reactable()

create_react <- function(df, var) {
    df %>% 
      summarize(Mean = mean({{var}}),
                SD = sd({{var}}),
                Min = min({{var}}),
                Max = max({{var}}),
                Total = length({{var}})) %>% 
      mutate_if(is.numeric, round, 2) %>% 
      reactable(columns = list(
        Mean = colDef(format = colFormat(separators = TRUE)),
        SD = colDef(format = colFormat(separators = TRUE)),
        Min = colDef(format = colFormat(separators = TRUE)),
        Max = colDef(format = colFormat(separators = TRUE)),
        Total = colDef(format = colFormat(separators = TRUE, suffix = " individuals"))
      ))
}

react_percent <- function(df, var) {
  df %>% 
    summarize(Mean = mean({{var}}),
              SD = sd({{var}}),
              Min = min({{var}}),
              Max = max({{var}}),
              Total = length({{var}})) %>% 
    mutate_if(is.numeric, round, 2) %>% 
    reactable(columns = list(
      Mean = colDef(format = colFormat(separators = TRUE, suffix = "%")),
      SD = colDef(format = colFormat(separators = TRUE, suffix = "%")),
      Min = colDef(format = colFormat(separators = TRUE, suffix = "%")),
      Max = colDef(format = colFormat(separators = TRUE, suffix = "%")),
      Total = colDef(format = colFormat(separators = TRUE, suffix = " individuals"))
      ))
}

baseline_tbl1 <- baseline_all_positive 

head(baseline_final)

```

```{r, extract descriptor variables, include=FALSE}
#age 

age <- baseline3 %>% 
  group_by(passport_id) %>% 
  mutate(number = row_number()) %>% 
  ungroup() %>% 
  pivot_wider(
    id_cols = passport_id,
    names_from = number,
    values_from = c(test_date, user_age),
    names_glue = "{.value}_{number}"
  ) 

age <- age %>% 
  select(passport_id,
         test_date_1,
         test_date_2,
         user_age_1,
         user_age_2)

str(age)

# school 

school <- baseline3 %>% 
  group_by(passport_id) %>% 
  mutate(number = row_number()) %>% 
  ungroup() %>% 
  pivot_wider(
    id_cols = passport_id,
    names_from = number,
    values_from = c(test_date, org_name),
    names_glue = "{.value}_{number}"
  ) 

school <- school %>% 
  select(passport_id,
         test_date_1,
         test_date_2,
         org_name_1,
         org_name_2)

# sport

sport <- baseline3 %>% 
  group_by(passport_id) %>% 
  mutate(number = row_number()) %>% 
  ungroup() %>% 
  pivot_wider(
    id_cols = passport_id,
    names_from = number,
    values_from = c(test_date, user_current_sport),
    names_glue = "{.value}_{number}"
  ) 

sport <- sport %>% 
  select(passport_id,
         test_date_1,
         test_date_2,
         user_current_sport_1,
         user_current_sport_2)
```

```{r, join baseline variables, include=FALSE}
blj_1 <- full_join(age, school)
blj_2 <- full_join(blj_1, sport)

baseline_final <- left_join(baseline_final, blj_2)

baseline_all_positive <- left_join(baseline_all_positive, blj_2)

```